[[bkgd]]
== Background and Introduction

For decades scientists and policymakers have been calling for more effective and efficient methods to monitor and address the global challenges of biodiversity loss and environmental degradation (https://doi.org/10.1126/science.1131946[Carpenter et al. 2006^], https://doi.org/10.1016/j.tree.2005.10.015[Pereira & Cooper 2006^], https://doi.org/10.1016/j.cosust.2018.02.005[Navarro et al. 2017^]). The Convention on Biological Diversity (CBD) has been a primary force behind the creation of systems to monitor changes in biodiversity and has served as a global assessor of the progress made toward the achievement of goals, such as the https://www.cbd.int/meetings/COP-10[Aichi Biodiversity Targets established in 2010^]. Despite wide-spread efforts to stem the tide of ecological decline, the CBD declared in its Global Biodiversity Outlook 5 (https://www.cbd.int/gbo5[CBD 2020c^]) that none of the 20 Aichi targets for biodiversity were fully achieved by the 2020 deadline. Only six of these targets were accomplished partially.

The failure of the global community to rise to the call of the CBD has been attributed to many factors, including gaps in and limited access to scientific knowledge, regional economic disparity, and a lack of political will (https://www.cbd.int/gbo5[CBD 2020c^], https://www.cbd.int/doc/c/73bc/335c/480a6a50d95d04478f4b3041/sbi-03-02-en.pdf[CBD 2020e^], https://ipbes.net/global-assessment[IPBES 2019^]). Widespread use of sensor-based observation systems, the rise of global biodiversity aggregation services, and novel applications for genetic and genomic discovery have helped to address some of these challenges (https://doi.org/10.1126/science.1256014[Turner 2014^], https://doi.org/10.1038/s41559-017-0176[Bush et al. 2017^]). Primary ecological and biodiversity-based data are far more discoverable than in years past (https://doi.org/10.1371/journal.pbio.1000309[Constable et al. 2010^]). The increase in data availability is necessary, but insufficient to meet the targets set to sustain natural capital.

To address the pressing crisis in biodiversity the CBD is developing a post-2020 global biodiversity framework to support an accelerated push for action with a new set of goals and targets to replace the Aichi targets. The Zero Draft of the framework (https://www.cbd.int/doc/c/efb0/1f84/a892b98d2982a829962b6371/wg2020-02-03-en.pdf[CBD 2020a^], https://www.cbd.int/doc/c/3064/749a/0f65ac7f9def86707f4eaefa/post2020-prep-02-01-en.pdf[CBD 2020b^]) builds upon the mission of the Strategic Plan for Biodiversity 2011-2020 (https://www.cbd.int/sp/[CBD 2010^]), retains the 2050 Vision and proposes five long-term goals with associated outcomes for 2030 and 2050, including 20 action targets through which the goals should be achieved.

Access to reliable, high-quality information is essential to achieve the goals of the post-2020 framework. The new Target 19 proposes to expand upon the partial successes towards achieving its previous version to “ensure that quality information, including traditional knowledge, is available to decision makers and public [sic] for the effective management of biodiversity through promoting awareness, education and research.” This information is indispensable, as the proposed framework presupposes that progress to attain the goals will be monitored over time. The assessment, development and use of appropriate biodiversity indicators (https://www.cbd.int/sbstta/sbstta-24/post2020-indicators-en.pdf[UNEP-WCMC & BIP 2020^]) will play an important role in the reporting processes.

A biodiversity indicator, as defined by the Biodiversity Indicators Partnership (https://www.cbd.int/doc/meetings/ind/ahteg-sp-ind-01/other/ahteg-sp-ind-01-bipnational-en.pdf[BIP 2011^]), is “a measure based on verifiable data that conveys information about more than itself”. Indicators provide a means to monitor and report on the state of biodiversity, the Earth’s ecological systems and the status of efforts to protect and preserve them. The BIP develops and ratifies key biodiversity indicators (https://www.cbd.int/doc/meetings/ind/ahteg-sp-ind-01/other/ahteg-sp-ind-01-bipnational-en.pdf[BIP 2011^]; https://www.cbd.int/sbstta/sbstta-24/post2020-indicators-en.pdf[UNEP-WCMC & BIP 2020^]) with the explicit purpose to assess the progress and success of the draft monitoring framework (https://www.cbd.int/sbstta/sbstta-24/post2020-monitoring-en.pdf[CBD 2020d^]) of the post-2020 global biodiversity framework (https://www.cbd.int/sbstta/sbstta-24/post2020-monitoring-en.pdf[CBD 2020d^]). Indicators inform policymakers to make justified decisions, measure the progress of national and regional efforts, raise awareness, and promote educational efforts (https://www.cbd.int/gbo2/[CBD 2006^]). Some indicators have been used for years and applied across different biodiversity-related conventions and processes (e.g. SDGs, IPBES, CITES, etc., see https://www.unep-wcmc.org/resources-and-data/global-biodiversity-indicator-mapping[Moul et al. 2018^]), while others are derived from the combined assessment of other indicators and indices. 

* The Zero Draft of the framework (https://www.cbd.int/doc/c/efb0/1f84/a892b98d2982a829962b6371/wg2020-02-03-en.pdf[CBD 2020a^], https://www.cbd.int/doc/c/3064/749a/0f65ac7f9def86707f4eaefa/post2020-prep-02-01-en.pdf[CBD 2020b^]) builds upon the mission of the Strategic Plan for Biodiversity 2011-2020 (https://www.cbd.int/sp/[CBD 2010^]), retains the 2050 Vision and proposes five long-term goals with associated outcomes for 2030 and 2050, including 20 action targets through which the goals should be achieved.
* Access to reliable, high-quality information is essential to achieve the goals of the post-2020 framework. The new Target 19 proposes to expand upon the partial successes towards achieving its previous version to “ensure that quality information, including traditional knowledge, is available to decision makers and public [sic] for the effective management of biodiversity through promoting awareness, education and research.” This information is indispensable, as the proposed framework presupposes that progress to attain the goals will be monitored over time. The assessment, development and use of appropriate biodiversity indicators (https://www.cbd.int/sbstta/sbstta-24/post2020-indicators-en.pdf[UNEP-WCMC & BIP 2020^]) will play an important role in the reporting processes.

In the context of the post-2020 framework a subset of headline quantitative indicators should be prioritized (https://www.cbd.int/sbstta/sbstta-24/post2020-indicators-en.pdf[UNEP-WCMC & BIP 2020^]). Such indicators should apply to all countries and allow prioritization of capacity and resource needs. A sufficient supply of high-quality data, common methodologies and data standards, and observation systems, must be available to ensure that headline indicators are comparable across the globe and to allow scalable reporting across space and time (https://www.cbd.int/doc/c/8cd2/6eab/663d8a4cc2d198b104225345/sbstta-24-inf-28-en.pdf[CBD 2021^]).

Timely publication of high-quality, comprehensive data is pivotal for indicators to be broadly applicable in aiding decision-making (https://doi.org/10.1126/science.1255772[Collen & Nicholson 2014^], https://doi.org/10.1111/cobi.13575[Stevenson et al. 2021^]). Data may suffer from a lack of completeness and from bias. A lack of completeness may result from two different aspects of the data acquisition and sharing workflow. First, data components may not be available and/or shared (e.g. missing fields in a database). Second, completeness may refer to geographic or temporal gaps during sampling events (e.g. a survey to determine presence of a given set of taxa at a national level where certain regions in the country are partially or not represented). Bias here refers to a systematic lack of information due to a sampling design that relies on incorrect assumptions, which may be taxonomic, geographic, temporal or environmental. Overall, providing timely high-quality data should take into consideration ways to address both data completeness and data bias (https://doi.org/10.1371/journal.pone.0041128[Nicholson et al. 2012^]). Furthermore, to ensure timeliness, data should conform to FAIR principles (Findability, Accessibility, Interoperability, and Reuse of digital assets, https://doi.org/10.1038/sdata.2016.18[Wilkinson et al. 2016^]) and encourage discoverability and accessibility to the information.

Biodiversity and ecological data are necessary for the creation of CBD’s biodiversity indicators to monitor progress to protect and preserve the Earth’s natural systems. The primary biodiversity data themselves, however, are not fit for use by policymakers and must first pass through the early stages of an information supply chain ([Kissling et al. 2018a^]) to become harmonized into derived data products that are ready for consumption. At the heart of the supply chain, between the primary biodiversity data and the indicators, sit a diverse set of analyses and processes that convert data from a wide-range of heterogeneous sources into homogenous and harmonized data products. These data products may be used in the generation of Essential Biodiversity Variables (EBVs), which, in turn, may be used to support the creation of biodiversity indicators. As the name implies, EBVs are an essential component of the information supply chain, yet their quality and usefulness are highly dependent upon the quality and quantity of the biodiversity data available for use (https://doi.org/10.1111/brv.12359[Kissling et al. 2018a^], https://doi.org/10.1038/s41559-018-0667-3[Kissling et al. 2018b^], https://doi.org/10.1016/j.cosust.2018.02.005[Navarro et al. 2017^], https://doi.org/10.1016/j.biocon.2016.07.014[Proença et al. 2017^]).

Essential Biodiversity Variables (EBVs) are measured and used to evaluate changes in the biological state across space, time and biological organization (https://doi.org/10.1007/s10531-017-1386-9[Schmeller et al. 2017^], https://doi.org/10.1016/j.ecoinf.2018.11.003[Hardisty et al. 2019^]). The measurement of some of these variables may result from the integration of multiple data sources, such as species occurrence data and remote-sensing observations. These data sources are aggregated and then assessed to evaluate a variable that describes temporal and spatial change that could not be derived from a single source alone ([Fernandez et al. in revision^]`REF?`). Fundamental characteristics of EBVs are the measurements that allow comparisons and assessment of change across various scales of time and space. In this context, monitoring initiatives such as the Earth Observation Networks (EONs) and Biodiversity Observation Networks (BONs) play a pivotal role in the acquisition of data and delivery of products that can be readily used in policy- and decision-making (https://doi.org/10.1016/j.tree.2017.10.008[Lindenmayer et al. 2017^], https://doi.org/10.1126/science.1162055[Scholes et al. 2008^], https://geobon.org/[GEO BON 2021^]). Despite ongoing efforts, challenges remain regarding the extent of species monitoring programs across different taxa and regions and their integration with the enormous amount of incidental occurrence data available through global biodiversity data platforms, such as the https://www.gbif.org[Global Biodiversity Information Facility^] (GBIF) (https://doi.org/10.1890/10.WB.23[Pereira et al. 2010^], https://doi.org/10.1016/j.cosust.2018.02.005[Navarro et al. 2017^]).

Scientists continue to struggle to find sufficient quantities of occurrences that contain the high-quality taxonomic and geographic data necessary to create EBVs and biodiversity indicators (https://doi.org/10.17161/bi.v8i2.4094[Ariño et al. 2013^], https://doi.org/10.1016/j.biocon.2016.07.014[Proença et al. 2017^]), despite the abundance of occurrence data (e.g. GBIF currently provides access to around 1.7 billion occurrence records). Leaving aside considerations of the quality of the available data, occurrences for many geographic areas or species are simply lacking, due, for example, to a lack of capacity to mobilize the data, limited access to difficult terrain, or restricted monitoring or inventory efforts (https://doi.org/10.1016/j.biocon.2013.06.034[Sousa-Baena et al. 2014^], https://doi.org/10.1371/journal.pone.0125629[Feeley 2015^]). Further, relevant details are often missing from the data, or they are captured in a way that renders them challenging to find, parse and process. These missing details are frequently, but not exclusively, related to associated sampling methods and taxonomic and geographic coverages. This information is essential to account for sources of bias and uncertainty in the data used to generate an EBV. Data and metadata gaps may result from historical data collection practices, collecting for purposes other than monitoring, loss of data over time or the exclusion of data during the publication process (e.g. the flattening of metadata to fit existing data-sharing standards and infrastructures, https://doi.org/10.3897/BDJ.6.e26826[Peterson et al. 2018^]).

GBIF is an international network and data infrastructure funded by the world’s governments to provide anyone, anywhere with open access to data about all types of life on Earth. Species occurrence data aggregated by GBIF have been used in research, education, and policy-making since it was established in 2001. These data have been used in nearly 6,000 peer-reviewed publications since 2008 (https://www.gbif.org/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true[GBIF Secretariat 2021^]). This primary biodiversity data also plays a critical role in the generation of information resources that guide the decision-making processes and the monitoring of progress to meet international commitments under the CBD and other multilateral environmental agreements. Growth in species occurrence records accessible through GBIF data serves as a primary indicator for tracking progress towards Target 19 of the https://www.cbd.int/sp/targets/[Aichi Biodiversity Targets^]. GBIF-mediated data also contribute to the development of several other indicators covering progress towards Aichi targets, including Target 5 (habitat loss and degradation), Target 9 (invasive alien species), Target 11 (protected areas), Target 12 (extinction risk) and Target 13 (genetic diversity). 

The process to develop and approve the post-2020 global biodiversity framework presents GBIF with a unique opportunity, especially given concerns that have been raised since the publication of the zero-draft and its update (https://www.cbd.int/doc/c/efb0/1f84/a892b98d2982a829962b6371/wg2020-02-03-en.pdf[CBD 2020a^], https://www.cbd.int/doc/c/3064/749a/0f65ac7f9def86707f4eaefa/post2020-prep-02-01-en.pdf[CBD 2020b^]). In particular, some stakeholders have called for revisions to certain goals, targets and indicators to ensure the framework’s effectiveness in different thematic areas and its overall goals (see https://doi.org/10.1126/science.abe1530[Díaz et al. 2020^], https://doi.org/10.3897/neobiota.62.53972[Essl et al. 2020^], https://doi.org/10.1016/j.biocon.2020.108654[Hoban et al. 2020^], https://doi.org/10.1111/conl.12778[Williams et al. 2020^]). As the premier data-sharing infrastructure for global biodiversity data, GBIF may position itself both to influence and to contribute to new and robust indicators of biodiversity while continuing to inform existing indicators. Biodiversity-related indicators and EBVs — and the ability to use them to achieve goals and targets — will benefit from high-quality biodiversity data brought together through GBIF.

When COP15 delegates approve the post-2020 framework, a new wave of biodiversity-related activities will begin; existing biodiversity indicators will be refreshed, new indicators may be constructed. To inform these indicators, primary biodiversity data and a range of EBVs and methods of analyses will be needed. GBIF, as an observer of the CBD, has been part of this conversation and has taken steps to ensure that GBIF, the members of the https://www.allianceforbio.org[_alliance for biodiversity knowledge_^] and all of the biodiversity data this collaboration has mobilized are prepared to contribute to the implementation of the post-2020 framework in meaningful ways. Key to these efforts is a better understanding of the landscape of data sources and relevant stakeholders involved in the development of indicators, as well as the dependencies among them, to help direct future collaborations and commitments.

In this study we identify projects and products that make use of primary biodiversity data to support the post-2020 biodiversity framework and how they inform indicators and information tools that address different CBD concerns. Also, we review and characterize the sources of primary biodiversity data used to inform indicators and other information products to identify where data use is redundant and how GBIF might provide data more effectively. Finally, we perform an analysis of the likely dependencies on primary biodiversity data within the post-2020 biodiversity framework, including primary biodiversity data and data from other disciplines, with an assessment of the intervening organizations and their roles in data collection, harmonization and delivery of primary biodiversity data, EBVs and indicators towards policy agendas.
