[[results]]
== Results

As we started to assess the 11 biodiversity indicators, several patterns emerged almost immediately and held true for the duration of the analysis (Tables 1 and 2). These patterns can be grouped into four themes that influence how biodiversity indicators are created and how the groups responsible for the maintenance of each indicator communicate with the broad community.

. Transparency influences both how EBVs and indicators are created, and how they are shared with the research and policy communities. Individuals attempting to understand how any given indicator was formulated, how it made use of primary biodiversity data, and which processes and analyses were applied to those data, have few clear pathways to find answers. Thus, many EBVs and indicators present themselves as ‘black boxes’ and require specialized knowledge to understand their inner workings. We present specific examples in the Discussion section below.
. The data sources used to create biodiversity indicators represent a broad diversity in topic and presentation (Table 1). We observed several strong patterns in the data sources and their host organizations (Tables 1 and 2).
.. Biodiversity data platforms are generally the primary sources of the biodiversity data used in indicator creation. These platforms, such as GBIF.org for biodiversity data, differ from the original publishers of the data in that they are not usually the stewards or sources of the primary biodiversity data. Organizations such as natural history museums, government collections, and non-governmental organizations often provide the primary data and publish them to biodiversity data platforms to ensure that these data have broad distribution and are easily discoverable. Platforms provide the broad community with access to open, licensed data that tend to be general in their taxonomic, geographical and temporal scopes, although there is significant variation in the quantity, quality and presentation of the data from one platform to another.
.. The data sources used to construct indicators are not limited to those provided as primary biodiversity data. Biodiversity data are used in combination with sources of other types of data from a variety of sources, such as distribution ranges and maps, land cover and land use imagery, climatic information, geographic administrative and political information, and socio-economic information. It is very common for biodiversity data to be used in conjunction with geographic and land use data, thus the quality of the locality data within each data set correlates with the quality of the output of the analyses performed for a given indicator.
.. Most primary data sources used in the indicators reviewed are freely accessible, yet the documentation of and access to the specific data actually used in the construction of the biodiversity indicators is often not available. This limitation presents challenges for the transparency of the creation processes and for communicating about each indicator (related to theme 1 above). A significant proportion of the data used in building some of the indicators comes from research published in closed-access scientific journals.
.. In almost all cases, the data sources used in indicator construction are generated, maintained and aggregated by governmental agencies or non-governmental organizations. Data that originate from or are maintained by private entities may be used in conjunction with public data, but there is little evidence to link any for-profit group to indicator creation.
