[[results]]
== Results

As we started to assess the 11 biodiversity indicators, several patterns emerged almost immediately and held true for the duration of the analysis (Tables 1 and 2). These patterns can be grouped into four themes that influence how biodiversity indicators are created and how the groups responsible for the maintenance of each indicator communicate with the broad community.

. Transparency influences both how EBVs and indicators are created, and how they are shared with the research and policy communities. Individuals attempting to understand how any given indicator was formulated, how it made use of primary biodiversity data, and which processes and analyses were applied to those data, have few clear pathways to find answers. Thus, many EBVs and indicators present themselves as ‘black boxes’ and require specialized knowledge to understand their inner workings. We present specific examples in the Discussion section below.
. The data sources used to create biodiversity indicators represent a broad diversity in topic and presentation (Table 1). We observed several strong patterns in the data sources and their host organizations (Tables 1 and 2).
.. Biodiversity data platforms are generally the primary sources of the biodiversity data used in indicator creation. These platforms, such as GBIF.org for biodiversity data, differ from the original publishers of the data in that they are not usually the stewards or sources of the primary biodiversity data. Organizations such as natural history museums, government collections, and non-governmental organizations often provide the primary data and publish them to biodiversity data platforms to ensure that these data have broad distribution and are easily discoverable. Platforms provide the broad community with access to open, licensed data that tend to be general in their taxonomic, geographical and temporal scopes, although there is significant variation in the quantity, quality and presentation of the data from one platform to another.
.. The data sources used to construct indicators are not limited to those provided as primary biodiversity data. Biodiversity data are used in combination with sources of other types of data from a variety of sources, such as distribution ranges and maps, land cover and land use imagery, climatic information, geographic administrative and political information, and socio-economic information. It is very common for biodiversity data to be used in conjunction with geographic and land use data, thus the quality of the locality data within each data set correlates with the quality of the output of the analyses performed for a given indicator.
.. Most primary data sources used in the indicators reviewed are freely accessible, yet the documentation of and access to the specific data actually used in the construction of the biodiversity indicators is often not available. This limitation presents challenges for the transparency of the creation processes and for communicating about each indicator (related to theme 1 above). A significant proportion of the data used in building some of the indicators comes from research published in closed-access scientific journals.
.. In almost all cases, the data sources used in indicator construction are generated, maintained and aggregated by governmental agencies or non-governmental organizations. Data that originate from or are maintained by private entities may be used in conjunction with public data, but there is little evidence to link any for-profit group to indicator creation.

Table 1. Summary of data sources types, organizations and data types feeding into indicators. For more details, see Supplemental Materials, https://docs.google.com/spreadsheets/d/1nAcCY5QO9P5yoTooaHZ0Zia717Mvy-cABOFKuuTBOGk/edit#gid=0.

Table 2. Summary of the characteristics of the data sources organizations. For more details, see Supp. Material.

3. The pathway for data moving from biodiversity data platforms into the analysis pipeline during the creation of a biodiversity indicator is not always linear. The use or sharing of datasets and data products between indicators magnifies issues of transparency, especially when primary biodiversity data is processed for the benefit of Indicator A and then Indicator A’s data products are used as the inputs for analysis for Indicator B. These relationships between indicators are not uncommon. For example, the relationship between the Species Habitat Index (SHI; produced by Map of Life; https://mol.org/) and the Bioclimatic Ecosystem Resilience Index (BERI; produced by CSIRO; https://www.csiro.au/) demonstrate how data and data product use can become intertwined (Figure 1A).
+ 
+ The SHI uses biodiversity data from GBIF and other biodiversity data platforms and individual data providers. That data is subjected to various analyses from which Map of Life produces various data products (new datasets) which are then used in part to create the SHI. Similarly, CSIRO takes biodiversity data from GBIF, combines it with data products developed by Map of Life and then uses them to create the BERI. The fact that both use data from GBIF directly demonstrates a likelihood of data overlap, while CSIRO’s use of data products from Map of Life that already include GBIF data demonstrates a circular use of data. Adding complexity to this process, both the SHI and BERI utilize data products from the creation of EBVs produced by GEO-BON, which also uses Map of Life data products. The effect of these circular and overlapping data uses essentially creates a ‘black box’ whose inner workings lack transparency and cannot be discerned easily, if at all. The analysis of the positive or negative effects on the accuracy and effectiveness of a given indicator produced with these types of relationships was not within the scope of this research.
+ 
+ The Agrobiodiversity Index is unique in that it follows a more complex path than other indicators (Figure 1B), as it builds not only on data and data products but also on other indexes (e.g. the Environmental Performance Index). Transparency becomes more important as the complexity of a given indicator, such as the Agrobiodiversity Index, is increased.


Figure 1. Data workflow / life cycle from data generation, through aggregation or compilation by different sources, to building of biodiversity-related indicators, and dependencies across the distinct organizations involved. A. Example for two of the indicators assessed: Species Habitat Indexa and Bioclimatic Ecosystem Resilience Index. B. Example for the Agrobiodiversity Index.

4. Finally, species occurrence data is one of many types of data used to generate EBVs and biodiversity indicators (Figure 2). The occurrence data used in these indicators can often be traced back to GBIF, either as direct downloads or as source material for secondary data products produced for EBVs or indicators. The occurrences themselves are derived from multiple sources; they can come from a biodiversity data platform directly (e.g. GBIF); they may be extracted from from surveys, inventories, and checklists; and from other maps, peer-reviewed publications, and even from personal research documentation, as demonstrated by the published sources used for the Species Habitat Index, produced by Map of Life (https://mol.org/datasets/). It is worth noting that when more than one platform is used, the result is often the use of shared or duplicate data, such as when data from GBIF and VertNet (http://vertnet.org/) are used (all records in VertNet are also in GBIF). Datasets used in conjunction with species occurrence data encompass a broad range of topics and sources. The use of various forms of geographic data are common, including LANDSAT, MODIS and CGIAR CSI (https://cgiarcsi.community/), climatic data (e.g. WorldClim, https://www.worldclim.org/), genetic resources (e.g. GENESYS, https://www.genesys-pgr.org/), and other environmental and agricultural datasets may be used (e.g. SoilGrids, https://soilgrids.org/; FAO, http://www.fao.org/home/en/: CIAT, https://ciat.cgiar.org/; see Table 1).

Figure 2. Types of data used for building the biodiversity-related indicators assessed in this study.
