[[discussion]]
== Discussion

The results of this analysis offer insight into the role of primary biodiversity data and other source materials used in the process of generating biodiversity indicators. A review of historic inputs of primary biodiversity data into CBD processes has revealed broad usage of broad usage of species occurrence data in generating biodiversity indicators. These data are used in conjunction with additional data sources that describe the environmental, genetic, species and geographic characteristics necessary to the focus of the indicator being constructed.

It is clear that biodiversity data platforms, such as GBIF, contribute to the development and use of EBVs and biodiversity indicators by making primary biodiversity data available openly. There remain, however, some challenges within the data and the ways in which the data-sharing community communicates with stakeholders from the local level to national and international policymakers. These challenges present several opportunities to improve the quality of available data and may serve to improve efforts to achieve the goals set in the post-2020 framework. 

=== Relevant and timely high-quality data

Data shared by data platforms and other organizations are critical resources in a wide range of research and scientific endeavors (Ball-Damerow et al. 2019, Graham et al. 2004, Heberling et al. 2021). GBIF, in particular, has played a leadership role in efforts to provide primary data in support of research since its creation in 2001. These efforts must continue in support of research and education globally. To become more relevant to the goals presented by the CBD in the post-2020 framework, however, there are several considerations that may be examined in regard to the types and quality of the data provided through global networks.

The process of building meaningful EBVs that can inform indicators needs data that can be reliably tracked across not just organism, space and time but also provenance; the latter includes relevant, complete and searchable metadata about the inventory process and the methods that produced those data. Over the last two decades there have been enormous efforts to mobilize biodiversity data, which have resulted in the availability of massive amounts of published data. Although data quality has long been recognized as a key step in the data mobilization process, there is still a large volume of data that still needs to be checked for quality and completeness. As a consequence, much of the data shared through biodiversity data platforms lack one or more of those four components, which limits or excludes their use in the creation of EBVs and biodiversity indicators. Furthermore, much of the data currently shared correspond to incidental records and lack any defined inventory or survey methods.

According to the UNEP-WCMC & BIP (2020), “The post-2020 global biodiversity framework will be implemented primarily at the national level. It is therefore important that the relative roles and suitability of both global and national indicators are considered.” The provision of data suitable for the national-level implementation strategy of the post-2020 framework that addresses the challenges of scalability will require biodiversity data platforms to improve the quality and completeness of available data and expand their infrastructure to include new data types and formats.

Data quality is an important consideration throughout the process of biodiversity data mobilization. GBIF and other organizations have devoted thousands of hours to train people working with data and to encourage a high standard for data published to public data portals (e.g. BID and BIFA Programmes, VertNet Training Curriculum, iDigBio Workflows). GBIF, for instance, provides a clear set of minimum requirements for published data (https://www.gbif.org/data-quality-requirements). Once data are published to the GBIF portal, automated processing routines flag data quality issues and produce a set of interpreted fields that use standardized terminology or recommended vocabularies. Such routines help to improve accuracy, increase the discoverability of data and ensure applicability of the data for use across a wide spectrum of research and policy endeavors. While these efforts should continue, they may not sufficiently improve the quality of data to make them useful in the post-2020 framework or EBVs and biodiversity indicators that support it.

For EBVs that use multi-variable analyses to aggregate and homogenize data across species, space and time, a taxon name, an event date and a set of coordinates are not enough to account for any bias or deficiencies in the available data. One way to help to overcome these biases is to publish occurrence and event records with metadata that describe the collection methodology and processes that are as rich as possible. Unfortunately, this type of correction will only be useful for certain types of analyses, and many species occurrence records that represent presence will still not be likely to be useful for EBVs that must account for absence data. For these EBVs, well-documented monitoring or inventory event data is needed. Certainly, not all data will be useful in this arena, nor are the biodiversity data platforms responsible to make all data high-quality, but some existing legacy data could be enhanced to become more fit for use. Further, data that are currently in the process of mobilization, and all of the data that have the potential to be mobilized, would benefit from an expanded set of best practices for publication.

As more monitoring data becomes available through the network, expanded best practices guidelines should include, but may not be limited to, how to share quality metadata containing details of the sampling methods employed and descriptions and provenance of the collected data. To make this practical, biodiversity data platforms will need to review and amend current data-sharing standards and practices, and upgrade their infrastructures to host and display new types of data and data formats. An example of a new standard that is under review for implementation is the Humboldt Core (Guralnick et al. 2017), which would allow more effective sharing of inventory data used for monitoring (Guralnick, pers. comm.).

Currently, many of the datasets published to biodiversity data platforms do not include the metadata adequate to the purpose of addressing bias in the creation of essential biodiversity variables. Several factors contribute to this limitation. In some cases, these data may not have been recorded at the time of collection, while in others it may not yet be digitized from field books and other physical media. For large collections that contain decades worth of data, the process of documenting the metadata for thousands of specimens and collection events may be far too onerous and burdensome. Further, not all data in these collections will have the associated metadata necessary for these improvements, but many institutions will have subsets of their collections that do (e.g. The Grinnell Survey and Re-Survey projects at the MVZ UCBerkeley, https://mvz.berkeley.edu/Grinnell/). To make these data more useful to efforts within the post-2020 framework, it may be worthwhile to encourage institutions to create “sub-collections” for these specific monitoring and inventory projects that they could publish separately from their larger corpus of data. Further, GBIF and other biodiversity data platforms may wish to place greater emphasis on the publication of past and current monitoring and inventory datasets with the expressed purpose of supporting EBV and biodiversity indicator creation. One way to accomplish this might be to strengthen ties with the research and monitoring communities that produce those data and encourage their participation in GBIF’s data publication programmes.

Even if these communities were to satisfy the need for more complete data in different formats, questions would remain about how homogeneous and repeatable the treatment of the same data can be in different contexts. As described above (see Results), the same data, from multiple sources, is being used by distinct organizations or collaborations to build EBVs and indicators, all of which contribute to the same overall goals within the post-2020 framework. Currently, stakeholders developing a given EBV or indicator treat the data independently and apply their own filters and quality checks, which may be more or less similar to those used by other stakeholders. If biodiversity data platforms could prepare species occurrence data in advance for EBV and indicator creation, as EBV-usable datasets, for example, better consistency and transparency might be achieved. In the context of this research, the term “EBV-usable” is meant as described in Kissling et al. (2018a), and refers to datasets compiled from relevant primary data with appropriate licenses that have undergone basic consistency and completeness checks (as opposed to EBV-ready datasets, Kissling et al. 2018a).

This preparation of data presents an opportunity for GBIF to partner with GEO BON and other research and policy organizations to better understand their specific data needs and reinforce their position as a primary resource for research and analysis-ready biodiversity data. A partnership of this sort might begin with the creation of a community consultation or conversation to identify the key data and data preparations that are needed for EBV generation, including what types of data or metadata are important and what data gaps need to be filled. The results of these consultations could help set future data mobilization goals and targets for GBIF and other data biodiversity data platforms. This conversation might also include identification of community training and capacity-building needs and strategies for addressing them most effectively. For instance, pre-formatted EBV-usable downloads could be provided for EBVs known to need specific subsets of data or datasets in certain formats. Datasets could be prefiltered and preprocessed so that they are readily compatible with other often used ecological or environmental data from data sources such as WorldClim, Landsat, soil grids, Genesys (genetic resources) and geographic regions. These datasets might also be validated against the GBIF/Catalogue of Life taxonomic backbone, which might help to simplify data preparation for EBV creators and remove the need for them to perform additional taxonomic validations.

=== Support the network

Accomplishing any of the data-related enhancements suggested above will require a concerted effort across the broad biodiversity research and conservation community. The fact that few of the CBD’s 2020 goals have shown discernable progress may be attributable, in part, to a disconnect between high-level policy and local activities. In fact, only a few nations have launched organized, country-level monitoring programs that embody shared goals and establish clear lines of communication between policymakers and local practitioners (e.g. national programs in New Zealand, <<lee,Lee et al. 2005>>; and Switzerland, Biodiversity Monitoring Switzerland 2021; also see Moussy et al. 2021). This disconnect works in both directions. Calls for data and the organization of large-scale monitoring efforts from entities such as the CBD often do not reach the local communities and organizations that might supply the data, so gaps remain (Mihoub et al. 2017). Meanwhile, local parties, unaware of these calls from national and international agencies, may not spontaneously contribute data from ongoing efforts, or if aware, they are unable to respond due to the limitations of funding mandates or geographic boundaries (Johnson et al. 2017).

A plethora of organizations with local foci have made major contributions to the amount of biodiversity data available through data-sharing networks. Much of this data was collected by local volunteers working for self-organized groups attempting to answer questions of local interest (Schmeller et al. 2009, Pocock et al. 2018, Kühn et al. 2008). While these groups can work in collaboration with one another, they are more often operating on their own outside of a larger national or international framework. Even with a national framework, however, there is no guarantee that a top-down monitoring effort will provide the data or policy results that are needed (Kühl et al. 2020) without an active network that can link local and national interests and facilitate communication between them.

One of GBIF’s most valuable assets is its global network of governments, institutions, and organizations engaged through the efforts of individuals within them. The GBIF network is the social system through which all data flow and the foundation upon which the success of its technical infrastructure resides. This network provides three opportunities that may make biodiversity data from GBIF more relevant to the post-2020 framework, the CBD and new biodiversity goals for 2030 and 2050.

One of these opportunities is the ability to mobilize more data, especially monitoring and inventory data at the local level. Historically, much of the biodiversity science community has been focused on the mobilization of data within established legacy collections, such as those in museums, laboratories and government agencies, which maintain data from the past to the present (Guralnick et al. 2007). As more of these legacy collections have been mobilized, attention has shifted toward monitoring and observation projects, including citizen science (e.g. NOAA’s Beach Watch, https://farallones.noaa.gov/science/beachwatch; SANBI’s Custodians of Rare and Endangered Wildflowers programme, https://bit.ly/3pcBAEO; Chandler et al. 2017) and to biodiversity-focused NGOs (e.g. CERMES, https://cavehill.uwi.edu/cermes; NatureFiji-MareqetiViti, https://naturefiji.org/). As pressure mounts to address questions about the status and trends of biodiversity, it is these data from local sources focused on the smaller-scale monitoring of national parks, waterways, and wildlands - data often collected by indigenous peoples and local communities with local knowledge - that are of critical importance in efforts to fill knowledge gaps and maintain on-going monitoring (Tengö et al. 2017, Hill et al. 2020, Brook & McLachlan 2008, Geldmann et al. 2021).

GBIF is in a unique position to leverage the node-based structure of its network to encourage and train these local agencies and individuals to share monitoring and survey data while applying the best practices for data capture, quality and mobilization. In regions or countries in which a node has not been established, localized institutional networks, nodes from within the same region or nodes from countries with a history of support and involvement for the local effort could contribute. Efforts of this sort have already begun via the BID and BIFA programmes, funded by the European Union and the Government of Japan, respectively. Additional funding and other resources could support and expand these efforts with the explicit purpose of mobilizing local biodiversity data and knowledge. Enabling indigenous peoples and local communities to become active contributors to biodiversity monitoring efforts through the CBD would certainly contribute to meeting the goals set for 2030 and 2050.

Like indigenous peoples and local communities, the private sector is an important source of biodiversity data. Currently, the majority of the data in the GBIF index come from non-profit and government agencies, yet private entities hold a great wealth of biodiversity knowledge in the form of environmental assessments, impact assessments, and other project-based analyses. GBIF has begun to engage with the private sector directly through several initiatives, such as Data4Nature (https://www.gbif.org/data4nature) in partnership with the Agence Française de Développment (https://www.afd.fr/en), and the publication of a guidance document to help private companies become publishers through the GBIF network (Figueira et al. 2020). In addition, some national governments have begun to mandate private sector data publication (e.g. Colombia) and financial institutions have created incentives for commercial entities to share non-sensitive data with GBIF and other national and global repositories (The Equator Principles Association 2020). These developments may present natural opportunities for the GBIF network to support the publication of these data, particularly in countries where a GBIF node exists. In countries or regions without a Node, the GBIF network might provide regional support and private sector help desk, may provide assistance.The CBD would benefit greatly, as would the development of EBVs and indicators that rely on biodiversity data, from a partnership with GBIF and other organizations working to engage the private sector. One key task of this partnership should be to continue to delineate and promote strategies to build upon existing collaborations with the private sector to bring their information holdings into the public sphere. 

A second opportunity of equal importance is to mobilize the GBIF network to turn a historically one-way communication pipeline into a more complete cycle. Currently, those organizations and individuals that mobilize data into biodiversity data-sharing portals are hard-pressed to determine when and how their data are being used by researchers, educators and policymakers. Data and communications about these data, tend to flow in one direction, from local data collection and mobilization to scientists and policymakers, with little to no communication in the opposite direction. GBIF and other biodiversity data platforms have made commendable efforts to track downloads of data and to report the citations of published works back to data publishers when they are made public (see GBIF citation guidelines, https://www.gbif.org/citation-guidelines and the #CitetheDOI campaign on Twitter and other social media, https://twitter.com/hashtag/citethedoi?f=live). GBIF is in the uncommon position to be able to continue to build trust across the network by communicating back to organizations and individuals at the local level about the uses of data. These communications could occur in many ways, including notifications that alert data publishers when their data have been used in the creation of EBVs, biodiversity indicators and other high-level policy documents, using tools similar to the GBIF citation widget (see https://www.gbif.org/article/1E6v02SFQyhupvB7JqDXPN/citation-widget). Another effective communication strategy could be the presentation of specific examples that demonstrate how high-quality data and associated metadata are really being used to influence science and policy as a part of capacity-building activities and other public events. These possibilities will remain only possibilities, however, if the network does not work toward greater transparency.

The third opportunity for the GBIF network is to mobilize the community to work toward greater transparency and traceability across the entire information supply chain. The creation of EBVs and biodiversity indicators is a complex process. As reported in the Results section, it is not uncommon for the processes and analyses used to generate these data and policy products to remain undocumented or hidden from public view view. Similarly it is equally difficult to know exactly which data were used in the processes and how. Over the last several years, calls have been made to address this lack of transparency (Navarro et al. 2017, Hardisty et al. 2019, Fernandez et al. In review). Each of these calls recognizes that the processes employed and the products produced demand treatments similar to the peer-review process used in academic journals, providing clear documentation, access to primary data and tools for analysis in the short- and long-term. A GBIF partnership with GEO BON, a leader in the facilitation of EBV generation, could be conceived with two key goals: 1) to promote the use of existing guidelines for citation and acknowledgement, and 2) to improve existing documentation or develop new best practices to accommodate new types and sources of data. Guidelines and best practices that follow FAIR principles and promote the full traceability of EBVs could go a long way toward the realization of the first two opportunities for GBIF network described above. Any partnerships and collaborations should reinforce the GBIF data users agreement by which all data users are required to “...publicly acknowledge, following the scientific convention of citing sources in conjunction with the use of the data, the Data Publishers whose biodiversity data they have used, where appropriate through use of a Digital Object Identifier (DOI) applying to the dataset(s) and/or data downloads” (https://www.gbif.org/terms/data-user).

Many individuals in the GBIF network are engaged in the processes of EBV and indicator generation, as well as in those of data acquisition and mobilization. They are likely to be sympathetic to the needs of both groups. With this level of understanding, these individuals should become a key link in promoting mutually beneficial working arrangements between data publishers and EBV and indicator creators. Seizing this opportunity would help both to provide high-quality EBV-useable data and to foster open communication and transparent documentation. If GBIF can take advantage of its relationships with these individuals and groups, the entire community of people in the information supply chain would profit. Benefits would include receiving recognition for data mobilization efforts and data products created; and an increase in the data traceability, which can improve the reproducibility and transparency of the science. Greater community engagement of this kind would build trust and encourage even greater levels of communication between the policy and research communities.

Data and data products should be assigned persistent identifiers to encourage increased recognition. Currently, GBIF assigns a DOI for every download performed, along with associated information that describes the full query used, including the date and time, number of records, the datasets that contributed to the download, Creative Commons designations and other terms of use and the EML metadata. These data about the query are archived by GBIF indefinitely, but actual downloads are maintained only for a six month period, although data users can request that specific downloads be archived indefinitely. For data sources other than large biodiversity data platforms, identifiers are often missing. In the past, the responsibility to archive or maintain the primary datasets used to create EBVs has fallen upon the organizations in charge of building them. This makes it easy for recognition of GBIF and other data providers to be passed over. Further, it adds to the issues of transparency that make it difficult to replicate the analyses completed for a given indicator because the datasets are no longer available. To remedy this, better communication should be fostered between GBIF, the CBD, BIP, IPBES, GEO BON and other collaborators that promote, build and use indicators, so that archiving of datasets used is secured. GBIF’s experience archiving datasets searches and their recent efforts to provide access to monthly snapshots of the GBIF corpus and derived datasets (https://www.gbif.org/derived-dataset/about), available via cloud services, may increase GBIF’s visibility in the CBD and further establish them as an important partner. Ideally, there could be some shared responsibility for these archives that would ensure availability of the data from different access points. Ultimately, a searchable archive of DOIs and associated datasets linked to EBVs and indicators may improve transparency, aid in the reproducibility of the scientific process and improve opportunities for comparisons of data or baselines over time. 
