[[conclusions]]
== Conclusions

This research has identified four main challenges to the use of primary biodiversity data in the development of EBVs and indicators (described in the Results section), each of which will be critical to the success of the post-2020 global biodiversity framework:

. Transparency is a critical issue at every stage in the information supply chain. Currently specialized knowledge is required to understand how data flow from data publishers through the processes used to create EBVs and biodiversity indicators.
. Data sources used in the creation of EBVs and biodiversity indicators are diverse, usually including biodiversity data platforms, with little data coming from the private sector to date. Data sources are generally available for free, although much data is available behind paywalls (e.g. journal access).
. The pathway from primary biodiversity data to indicator is complicated, the information supply chain is not linear.
. Data duplication and circular usage is common, yet data traceability from the providers of primary biodiversity data to their use in EBVs and indicators is challenging.

Several actions could help to overcome these challenges: 

* An opportunity exists for GBIF to partner with GEO BON and other intergovernmental agencies and NGOs to facilitate further community-wide discussion and continue efforts to identify the key data and data preparations needed to support EBVs, biodiversity indicators, and other related research and policy-focused products. While one-off meetings have occurred in the space, a more persistent working group approach would be more effective. GEO BON has a Data Task Force, but that group has a broad remit and the suggested working group or task force is narrower in application. The new working group might include stakeholders from the scientific and policy communities, as well as a broad spectrum of participants from local-level organizations. This initiative should focus on a series of community consultations hosted by GBIF and GEO BON, with the support of the alliance for biodiversity knowledge, and facilitated by the new working group with a focus on identifying the types of data and metadata needed, the data gaps to fill, and the stakeholders most able to address these needs. Documenting the results of these consultations and a draft set of mobilization goals for community review could refocus existing data collection and mobilization initiatives or guide new ones.
* A second opportunity for a GBIF-GEO BON partnership, along with the TDWG community (https://www.tdwg.org/), is the preparation of a set of guidelines in two specific areas:
** Best practices that support the data collection and mobilization activities identified in the community consultations as described above. These practices would clarify the most effective methods to collect, document, validate, and mobilize data needed for EBV and indicator generation. This process should include individuals and organizations actively engaged in the process of data collection and curation, especially those individuals well-positioned to communicate and promote the use of these best practices in the field.
** Best practices for building greater transparency and recognition into the processes used to generate EBVs and biodiversity indicators, with a focus on establishing and implementing consistent methods. Community participants should include those individuals and groups responsible for the development of harmonized data products, EBVs and indicators. Additional participants should include members of the data curation community and clearly articulate the importance of transparency and attribution for members of the FAIR data community.
* Data from organized and well-documented monitoring and inventory events are critical for many EBVs and other analyses of trends over space and time. Biodiversity data platforms, such as GBIF, should join ongoing conversations focused on community monitoring activities because of the strong alignment of those models with existing GBIF publishing efforts. A recent paper by Kühl et al. (2020) calls for a model that focuses on opportunistic and semi-structured observations, mapping and strategic long-term data collection at single sites for increased spatiotemporal coverage, all managed by heterogeneous partners that can work together to align their priorities and goals. Another approach could identify new and existing sources of these types of data and to help the community to build capacity to provide those data with high-quality metadata, perhaps using the best practices established by the partnerships described above.
* In conjunction with efforts to mobilize more monitoring data, biodiversity data platforms might provide a series of curated datasets that contain both monitoring and ad hoc species occurrence data that meet a particular standard of quality and fitness for use. This standard could be determined by individual platforms or by the best practices for data collection and mobilization detailed above. These datasets might focus on national and regional scales and should be archived by one or more organizations publicly (e.g. GEO BON, GBIF). Each dataset should have a DOI assigned and be accompanied by a complete list of credits and attributions.
* As engagement increases between members of the community to establish best practices, new data products and expanded community discussion, it is critical to include indigenous peoples and local communities to facilitate mutually beneficial connections with researchers and policymakers, as highlighted by the UNESCO Recommendation on Open Science (UNESCO 2021). This can take the form of invitations to participate in the consultations described above, but engagement is likely to be limited at best. Instead, an organized effort to engage local and indegenous communities could begin within larger networks, such as GBIF’s global network in partnership with organizations with greater experience working with indigenous communities (e.g. CBD,United Nations) framed by the CARE principles (https://www.gida-global.org/care). GBIF can play an important role in the adoption of these principles within data workflows and how to highlight mechanisms that support the implementation through its global network. Members of the network who possess knowledge of specific local communities could be enlisted to serve as a conduit between those local individuals and groups and the greater data-sharing community. An individual with local knowledge and ties to the local community in a given country might be identified within the GBIF network. That person could then be supported, financially or through a formal designation, to act on behalf of the broad community to engage with those local groups to begin a conversation about the knowledge possessed within the community and what they would be willing to share. In support of that sharing, the deputy may also learn about the needs of the community and work to establish partnerships with the research and data mobilization communities to build capacity building and provide training necessary to meet local needs.
* The private sector is a source of an exceptional amount of biodiversity data from ad hoc observations and long-term monitoring that is largely unavailable for research and policymaking currently. Some biodiversity data platforms are actively engaging this community to bring their data into open data portals (e.g. GBIF through partnerships such as Data4Nature, https://www.gbif.org/data4nature; UNEP-WCMC Proteus Partnership, https://www.proteuspartners.org/). As a part of these efforts, GBIF and others should continue to encourage their integration into the larger community conversation, the use of best practices in data collection, and participation in growing initiatives such as the Equator Principles (https://equator-principles.com).
* A final action item is the development of a credit and attribution model created by biodiversity data platforms, mobilizers, data users (including organizations such as GEO BON and the CBD that facilitate EBV and indicator creation) and academic journals and other publishers. This collaborative effort should build upon the efforts of groups that have made advances in attribution through the continued use of DOIs and other credit-focused strategies. The growing community of practice focused on data citations includes initiatives such as #CiteTheDOI promoted by GBIF, COPDESS (https://copdess.org/), Make Data Count (https://makedatacount.org/) and a body of literature in support of giving credit where credit is due (Data Citation Synthesis Group 2014, McNutt et al. 2016, Vannan et al. 2020). Journal publishers may hold the greatest leverage to incentivize transparency and recognition, but they will need to be guided by other groups within the community to implement new practices.
